add_python_test(starclusterconfig PLUGIN cumulus)
add_python_test(job PLUGIN cumulus)
add_python_test(cluster PLUGIN cumulus)
add_python_test(script PLUGIN cumulus)
add_python_style_test(pep8_style_cumulus "${PROJECT_SOURCE_DIR}/plugins/cumulus/server")