- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    cluster_state: running
    cluster_region: us-west-2
    instance_type: t2.medium
    ec2_pod_spec:
      key: kotfic-NEX
      rules:

        - proto: tcp # ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

        - proto: all
          group_name: ec2_pod_default

      hosts:
        head:
          type: "{{ instace_type }}"

        data:
          type: "{{ instance_type }}"
          count: "{{ instance_count }}"
  roles:
    - role: ec2-pod
      default_ssh_key: "{{ ec2_pod_spec.key }}"
      name: "default"
      # passed in from deployment script
      state: "{{ cluster_state }}"
      region: "{{ cluster_region }}"
      default_image: ami-e0f7e081
      rules: "{{ ec2_pod_spec.rules }}"
      hosts: "{{ ec2_pod_spec.hosts }}"
