- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  roles:
    - role: ec2-pod
