---

  - name: set ec2 pod specification
    set_fact:
        ec2_pod_spec:
            key: kotfic-NEX
            rules:

              - proto: tcp # ssh
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0

              - proto: all
                group_name: ec2_pod_default

            hosts:
              head:
                type: t2.medium

              data:
                type: t2.medium
                count: 1
