language: python
python:
    - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

sudo: false

compiler:
    - gcc
before_install:
    # First install Girder
    - pushd "${HOME}/build"
    - git clone https://github.com/girder/girder.git
    - pushd "${HOME}"
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGO_VERSION}.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version
    - export IGNORE_PLUGINS=celery_jobs,geospatial,google_analytics,hdfs_assetstore,jquery_widgets,meta
    - girder/scripts/InstallPythonRequirements.py --mode=dev --ignore-plugins=${IGNORE_PLUGINS}
    # Symlink plugin
    - popd
    - pwd
    - ln -s `pwd`/girder/cumulus "${HOME}/build/girder/plugins/cumulus"
    # Install CMake
    - pushd "${HOME}"
    - curl "http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - cmake --version
install:
    - pwd
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt
script:
    # Update PYTHONPATH to include cumulus module
    - export PYTHONPATH=`pwd`
    - mkdir _build
    - cd _build
    - cmake -DBUILD_JAVASCRIPT_TESTS:BOOL=OFF -DPYTHON_COVERAGE:BOOL=ON -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/build/girder"
    - ctest -R cumulus -VV


