language: python
python:
    - "3.6"

cache:
  directories:
    - $HOME/.cache

sudo: false

compiler:
    - gcc

before_install:
    # Update pip
    - pip install -U pip
    # First install Girder
    - pushd "${HOME}/build"
    - git clone https://github.com/girder/girder.git
    - export IGNORE_PLUGINS=celery_jobs,geospatial,google_analytics,hdfs_assetstore,jquery_widgets,meta
    - pushd girder
    - pip install -r requirements-dev.txt
    - pip install .
    - pip install girder-client
    - popd
    - popd
    # Install mongodb
    - CACHE=$HOME/.cache source ./scripts/install/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version
    # Install CMake
    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source ./scripts/install/install_cmake.sh
install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt
    - python setup.py clean install
    # Install girder plugins
    - pushd girder
    - pip install `pwd`/cumulus # Install this one first as others depend on it
    - ls | xargs -n1 -I {} pip install `pwd`/{}
    - popd
script:
    - export BOTO_CONFIG=/dev/null
    - mkdir _girder_build
    - pushd _girder_build
    - cmake -DBUILD_JAVASCRIPT_TESTS:BOOL=OFF -DJAVASCRIPT_STYLE_TESTS:BOOL=OFF -DPYTHON_COVERAGE:BOOL=ON -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/build/girder"
    - ctest -R cumulus -VV
    - popd
    # Now test cumulus package
    - mkdir _cumulus_build
    - cd _cumulus_build
    - cmake -DPYTHON_COVERAGE:BOOL=OFF -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/build/Kitware/cumulus"
    - ctest -VV
