language: python
python:
    - "2.7"
    - "3.4"

cache:
  directories:
    - $HOME/.cache

sudo: false

compiler:
    - gcc

before_install:
    # Update pip
    - pip install -U pip
    # First install Girder
    - pushd "${HOME}/build"
    - git clone https://github.com/girder/girder.git
    - export IGNORE_PLUGINS=celery_jobs,geospatial,google_analytics,hdfs_assetstore,jquery_widgets,meta
    - pip install -r girder/requirements.txt
    - pip install -r girder/requirements-dev.txt
    - pip install girder/
    - CACHE=$HOME/.cache source $HOME/build/girder/scripts/install_mongo.sh
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version
    - pip install girder/clients/python
    # Install plugins
    - popd
    - pushd girder
    - ls | xargs -n1 -I {} ln -s `pwd`/{} $HOME/build/girder/plugins/{}
    - popd
    # Install CMake
    - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $HOME/build/girder/scripts/install_cmake.sh
install:
    - pwd
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt
    - python setup.py clean install
script:
    - export BOTO_CONFIG=/dev/null
    - mkdir _girder_build
    - pushd _girder_build
    - cmake -DBUILD_JAVASCRIPT_TESTS:BOOL=OFF -DJAVASCRIPT_STYLE_TESTS:BOOL=OFF -DPYTHON_COVERAGE:BOOL=ON -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/build/girder"
    - ctest -R cumulus -VV
    - popd
    # Now test cumulus package
    - mkdir _cumulus_build
    - cd _cumulus_build
    - cmake -DPYTHON_COVERAGE:BOOL=OFF -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/build/Kitware/cumulus"
    - ctest -VV
