- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    cluster_state: running
    cluster_region: us-west-2
  pre_tasks:
    - include: pod_config.yml
  roles:
    - role: ec2-pod
      default_ssh_key: "{{ ec2_pod_spec.key }}"
      name: "default"
      # passed in from deployment script
      state: "{{ cluster_state }}"
      region: "{{ cluster_region }}"
      default_image: ami-e0f7e081
      rules: "{{ ec2_pod_spec.rules }}"
      hosts: "{{ ec2_pod_spec.hosts }}"
