- name: Install grid engine packages on exec node
  apt:
    name="{{ packages }}"
    state=present
    update_cache=yes
  become_user: root
  vars:
    packages:
    - gridengine-client
    - gridengine-exec
  tags:
    - exec

- name: Stop execd
  service: name=gridengine-exec state=stopped


- name: Template and install act_qmaster configuration file
  template: src=act_qmaster dest=/var/lib/gridengine/default/common/act_qmaster group=sgeadmin owner=sgeadmin force=yes
  become_user: root
  tags:
    - exec

- name: Start execd
  service: name=gridengine-exec state=started

- name: Install NFS client
  apt: name=nfs-common
  become_user: root
  tags:
    - exec
    - nfs-client

- name: Mounting data directories from master
  become_user: root
  mount:
    name: "{{ item }}"
    src: "{{ hostvars[groups['master'][0]].private_ip }}:{{ item }}"
    fstype: nfs
    state: mounted
  with_items: "{{ master_nfs_exports }}"
  when:
    - inventory_hostname != groups['master'][0]
  tags:
    - exec
    - nfs-client

- name: Generate SSH key for access between nodes
  user: name=ubuntu generate_ssh_key=yes
  tags:
    - exec

# - name: Check master key
#   debug:
#     msg: "{{master_ssh_key}}"

- name: Add key to authorize_key file
  become_user: ubuntu
  shell: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  tags:
    - exec

- name: Add all host IPs to known_hosts
  become_user: ubuntu
  shell: ssh-keyscan -H {{hostvars[item].private_ip|default(hostvars[item].ansible_hostname)}} >> ~/.ssh/known_hosts
  with_items:
    - "{{ groups.exec | default([]) + groups.master }}"
  tags:
    - exec

- name: Add all hostnames to known_hosts
  become_user: ubuntu
  shell: ssh-keyscan -H {{hostvars[item].private_dns_name|default(hostvars[item].ansible_fqdn)}} >> ~/.ssh/known_hosts
  with_items:
    - "{{ groups.exec | default([]) + groups.master }}"
  tags:
    - exec

# - name: Copy over ssh config
#   become_user: ubuntu
#   copy: src=ssh_config dest=~/.ssh/config
#   tags:
#     - exec
