- name: Install mpich2 on all nodes
  apt:
    name="{{ packages }}"
    state=present
    update_cache=yes
  become_user: root
  vars:
    packages:
    - build-essential
    - mpich2
  tags:
    - mpich2
