---
- hosts: head
  tasks:
    - name: Fail if volume_id is not set
      fail:
        msg: "Volume ID must be passed in as volume_id"
      when: volume_id is not defined or volume_id == ""

    - name: Fail if instance_id is not set
      fail:
        msg: "Instance ID must be passed in as girder_instance_id"
      when: instance_id is not defined or instance_id == ""

    - name: Fail if path is not set
      fail:
        msg: "Path must be passed in as path"
      when: path is not defined or path == ""

    - block:
        # make local action
        - ec2_vol:
            id: "{{ volume_id }}"
            region: "{{ region }}"
            instance: "{{ instance_id }}"
            device_name: /dev/xvdf
          delegate_to: localhost
          register: vol

        - filesystem:
            fstype: ext4
            dev: /dev/xvdf
          become: yes
          become_user: root

        - mount:
            name: "{{ path }}"
            src: /dev/xvdf
            state: mounted
            fstype: ext4
            opts: "rw,exec"
          become: yes
          become_user: root

        - file:
            state: directory
            path: "{{ path }}"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: 0755
          become: yes
          become_user: root

        - girder:
            apiUrl: "{{ girder_api_url }}"
            token: "{{ girder_token }}"
            put:
              path: "volumes/{{ girder_volume_id }}/clusters/{{ girder_cluster_id }}/attach/complete"
              data:
                path: "{{ path }}"
          delegate_to: localhost
          when: girder_api_url is defined and girder_token is defined and girder_volume_id is defined and girder_cluster_id is defined
      rescue:
        - girder:
            apiUrl: "{{ girder_api_url }}"
            token: "{{ girder_token }}"
            patch:
              path: "volumes/{{ girder_volume_id }}"
              data:
                ec2:
                  status: 'error'
                  msg: 'An error occured while attaching the volume, please check the logs'
          delegate_to: localhost
          when: girder_api_url is defined and girder_token is defined and girder_volume_id is defined
