---
- hosts: head
  tasks:
    - name: Fail if profile ID not set
      fail:
        msg: "Profile ID must be passed in as profile_id"
      when: profile_id is not defined or profile_id == ""

    - name: Fail if girder volume ID is not set
      fail:
        msg: "Girder Volume ID must be passed in as girder_volume_id"
      when: girder_volume_id is not defined or girder_volume_id == ""

    # make local action
    - ec2_vol:
        id: "{{ volume_id }}"
        region: "{{ region }}"
        instance: "{{ instance_id }}"
        device_name: /dev/xvdf
      delegate_to: localhost
      register: vol

    - filesystem:
        fstype: ext4
        dev: /dev/xvdf
      become: yes
      become_user: root

    - mount:
        name: "{{ path }}"
        src: /dev/xvdf
        state: mounted
        fstype: ext4
        opts: "rw,exec"
      become: yes
      become_user: root

    - file:
        state: directory
        path: "{{ path }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      become: yes
      become_user: root


# Patch the volume ID back to girder
#    - girder:
#        apiUrl: "{{ girder_api_url }}"
#        token: "{{ girder_token }}"
#        patch:
#          path: "volumes/{{ girder_volume_id }}"
#          data:
#            ec2:
#              instance_id: "<< add me >>"
#      when: girder_api_url is defined and girder_token is defined
