- name: Setup groups for gridengine playbook
  hosts: localhost
  tasks:
  # - debug: var=groups
  - add_host:  name={{item}} groups=master
    with_items: "{{groups['head']}}"
  - add_host:  name={{item}} groups=exec
    when: "'data' in groups"
    with_items: "{{groups['data']}}"

- name: Master setup
  hosts: master
  vars:
    # Set up the NFS exports
    master_nfs_exports: "{{ master_nfs_exports_extra | default([]) | union(['/home']) }}"
  become: yes
  roles:
    - master

- name: Install mpich2
  hosts:
    - master
    - exec
  become: yes
  roles:
    - mpich2

- name: Exec host setup
  hosts:
    - master
    - exec
  vars:
    # Set up the NFS exports
    master_nfs_exports: "{{ master_nfs_exports_extra | default([]) | union(['/home']) }}"
  become: yes
  roles:
    - exec
